export const ADMIN_DISHES_REQUEST = 'ADMIN_DISHES_REQUEST'
export const ADMIN_DISHES_SUCCESS = 'ADMIN_DISHES_SUCCESS'
export const ADMIN_DISHES_FAIL = 'ADMIN_DISHES_FAIL'

export const ALL_DISHES_SUCCESS = 'ALL_DISHES_SUCCESS'
export const ALL_DISHES_REQUEST = 'ALL_DISHES_REQUEST'
export const ALL_DISHES_FAIL = 'ALL_DISHES_FAIL'

export const NEW_DISH_REQUEST = 'NEW_DISH_REQUEST'
export const NEW_DISH_SUCCESS = 'NEW_DISH_SUCCESS'
export const NEW_DISH_RESET = 'NEW_DISH_RESET'
export const NEW_DISH_FAIL = 'NEW_DISH_FAIL'

export const DELETE_DISH_REQUEST = 'DELETE_DISH_REQUEST'
export const DELETE_DISH_SUCCESS = 'DELETE_DISH_SUCCESS'
export const DELETE_DISH_RESET = 'DELETE_DISH_RESET'
export const DELETE_DISH_FAIL = 'DELETE_DISH_FAIL'

export const UPDATE_DISH_REQUEST = 'UPDATE_DISH_REQUEST'
export const UPDATE_DISH_SUCCESS = 'UPDATE_DISH_SUCCESS'
export const UPDATE_DISH_RESET = 'UPDATE_DISH_RESET'
export const UPDATE_DISH_FAIL = 'UPDATE_DISH_FAIL'

export const DISH_DETAILS_REQUEST = 'DISH_DETAILS_REQUEST'
export const DISH_DETAILS_SUCCESS = 'DISH_DETAILS_SUCCESS'
export const DISH_DETAILS_FAIL = 'DISH_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'