export const ALL_DISHES_SUCCESS = 'ALL_DISHES_SUCCESS'
export const ALL_DISHES_REQUEST = 'ALL_DISHES_REQUEST'
export const ALL_DISHES_FAIL = 'ALL_DISHES_FAIL'

export const DISH_DETAILS_REQUEST = 'DISH_DETAILS_REQUEST'
export const DISH_DETAILS_SUCCESS = 'DISH_DETAILS_SUCCESS'
export const DISH_DETAILS_FAIL = 'DISH_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'